[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "test_gurobi: marks tests as run only when we have a Gurobi license (deselect with '-m \"not test_gurobi\"')"
]

[tool.isort]
profile = "black"