name: Sphinx documentation build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with: 
          pre-build-command: "apt-get update -y --allow-releaseinfo-change && apt-get install -y git && pip install sphinx==4.0"
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/_build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
